# Using latest version of node run in alpine
FROM node:alpine


WORKDIR /app

 
COPY ./music-app/package*.json ./

RUN npm install

COPY ./music-app/ .

EXPOSE 3000

#Run 'npm start' when the container starts.
CMD [ "npm", "run", "start" ]